image: docker:latest
stages:
  - build

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

before_script:
    - if [ "$CI_COMMIT_REF_NAME" != "master" ] && [ -z "$CI_COMMIT_TAG" ]; then BRANCH="/$CI_COMMIT_REF_NAME"; fi
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build_x86: &build_x86
  stage: build
  tags: [ docker ]
  script:
    - docker build -t "$CI_REGISTRY_IMAGE$BRANCH:latest" .
    - docker push "$CI_REGISTRY_IMAGE$BRANCH:latest"
    # Publish tag
    - >
      if [ ! -z "$CI_COMMIT_TAG" ]; then
        docker tag "$CI_REGISTRY_IMAGE$BRANCH:latest" "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG";
        docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"; fi
    # Publish to dockerhub
    - >
      if [ -z "$BRANCH" ] && [ ! -z "$DOCKERHUB_PASSWORD" ]; then
        docker login -u "$DOCKERHUB_LOGIN" -p "$DOCKERHUB_PASSWORD";
        docker tag "$CI_REGISTRY_IMAGE$BRANCH:latest" thann/yay;
        docker push thann/yay; fi

